name: Deploy Project
on:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-build-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{ runner.OS }}-build-${{ runner.OS }}-
      - name: Build
        run: |
          env
          yarn install
          yarn build
          mkdir -p dist
          cp -rf packages/root-config/dist/* dist/
          cp -rf packages/navbar/dist dist/navbar
          cp -rf packages/auth/dist dist/auth
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
